server:
  contextPath: /practitioner-service
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: practitioner-service

management:
  security:
    enabled: false

logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG