

# Builder image
FROM maven:3.9.9-eclipse-temurin-11-alpine

COPY pom.xml ./
COPY src ./src

RUN mvn clean package -DskipTests


# Final image
FROM eclipse-temurin:11-jdk-alpine

COPY --from=builder /target/*.jar app.jar

EXPOSE 8085

ENTRYPOINT ["java", "-jar", "app.jar"]
