apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # Nom de la ressource
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medical-record-service
  template:
    metadata:
      labels:
        app: medical-record-service
    spec:
      containers:
        - name: medical-record-service
          image: <registry>/<username>/medical-record-service:latest
          ports:
            - containerPort: 8083
